# Generated by Django 4.2.6 on 2023-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyogSaarthi', '0002_alter_candidateprofile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
