# Generated by Django 4.2.6 on 2023-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyogSaarthi', '0003_candidateprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='files')),
            ],
        ),
    ]
