# Generated by Django 4.2.6 on 2023-10-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyogSaarthi', '0007_employerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('organization_type', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('PSU', 'PSU')], max_length=10)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=500)),
                ('openings', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
