# Generated by Django 4.2.6 on 2023-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyogSaarthi', '0009_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='UdyogSaarthi.jobs'),
        ),
    ]
