# Generated by Django 4.2.6 on 2023-10-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UdyogSaarthi', '0010_candidateprofile_applied_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='posted_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UdyogSaarthi.employerprofile'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
