# Generated by Django 4.2.6 on 2023-10-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UdyogSaarthi', '0011_jobs_posted_by_delete_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='posted_by',
        ),
    ]
