# Generated by Django 4.2.6 on 2023-10-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UdyogSaarthi', '0012_remove_jobs_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='applied_jobs',
        ),
    ]
